@startuml Banking System

class BankSystem {
    '// Attributes
    == Attributes ==
    - boolean open              //open/close account
    - Vector<Account> accounts
    '// Methods
    == Methods ==
    + deposit(Account, double)
    + boolean withdraw(Account, double)
    + createAccount()
}

class Teller {
    '// Attributes
    == Attributes ==
    - String ID
    - String name
    - String password
    '// Methods
    == Methods ==
    .. Getters ..
    + String getID()
    + String getName()
    + String getPassword()
    .. Setters ..
    + void setID(String)
    + void setName(String)
    + void setPassword(String)
    + getMoney()
    + openAccount()
    + closeAccount()
    + getCustomerInfo(Customer)
}

class ATM {
    '// Attributes
    == Attributes ==
    - double balance
    '// Methods
    == Methods ==
    
}

class Customer {
    '// Attributes
    == Attributes ==

    '// Methods
    == Methods ==
    
}

class Account {
    '// Attributes
    == Attributes ==

    '// Methods
    == Methods ==
    
}

@enduml

@startuml Banking System 2
class Login {
- String username
- String password
+ Login()
}

class Name {
- String first
- String middle
- String last
}

class Address {
- String street
- String city
- int zip
}

enum ActionType {
WITHDRAW
DEPOSIT
OTHER
}

class Action {
- ActionType type
- Date date
}

class Customer {
- Login cLogin
- Address cAddress
}
Customer "1" <-- "0..*" Name

@enduml
